### ISSUE TITLE
Discord Link Invalid

### ISSUE THREAD

**Issue by nikolaischunk** [beCoditive/random-jokes-api#2]
Steps to reproduce:
Open one of the two links in the ReadME
![image](https://user-images.githubusercontent.com/58025175/145363754-0932f1b7-427d-4e32-a338-e4932184336f.png)
Code that summoned the error:
Well no Code directly, but the the Link in the Readme.md is outdated.
![image](https://user-images.githubusercontent.com/58025175/145364092-009320b3-cb2f-4726-b0ea-20900a9dc1fe.png)

The complete error:
![image](https://user-images.githubusercontent.com/58025175/145364188-2a7af462-64f0-4955-b96b-6f122d660fff.png)

**Comment by Max2408** [comment]
the discord support server has been deleted. As soon as we create new server we will change it.
